name: LiboLibo

options:
  bundleIdPrefix: me.libolibo
  deploymentTarget:
    iOS: "18.0"
  developmentLanguage: ru
  createIntermediateGroups: true

settings:
  base:
    DEVELOPMENT_TEAM: ""

targets:
  LiboLibo:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: LiboLibo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: me.libolibo.app
        TARGETED_DEVICE_FAMILY: "1,2"
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Либо-Либо
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGNING_ALLOWED: NO
